export const PAKISTAN_CITIES = [
  "Karachi",
  "Hyderabad",
  "Sukkur",
  "Larkana",
  "Nawabshah",
  "Mirpur Khas",
  "Thatta",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Multan",
  "Gujranwala",
  "Sialkot",
  "Bahawalpur",
  "Sargodha",
  "Sheikhupura",
  "Rahim Yar Khan",
  "Gujrat",
  "Sahiwal",
  "Dera Ghazi Khan",
  "Jhelum",
  "Murree",
  "Islamabad",
  "Peshawar",
  "Abbottabad",
  "Mardan",
  "Kohat",
  "Dera Ismail Khan",
  "Swat (Mingora)",
  "Naran",
  "Kaghan",
  "Nathia Gali",
  "Chitral",
  "Quetta",
  "Gwadar",
  "Ziarat",
  "Gilgit",
  "Skardu",
  "Hunza",
  "Muzaffarabad",
  "Mirpur (AJK)",
  "Rawalakot",
];